-- Basic Neovim Settings
require("plugins")
require("settings")
require("keymappings")
require("autocommands")
require("colors")

-- Plugin Settings
require("user.bufferline")
-- require("user.nvim-gps")
require("user.nvim-tree")
require("user.which-key")
require("user.gitsigns")
require("user.cmp")
require("user.alpha")
require("user.nvim-treesitter")
require("user.impatient")
require("user.numb")
require("user.nvim_comment")
require("user.indentline")
require("user.nvim-autopairs")
require("user.toggleterm")
require("user.lualine")
require("user.telescope")
require("user.notify")
require("user.lsp")
require("user.jaq")
