require("settings")
require("colors")
require("plugins")
require("keymappings")

require("user.bufferline")
require("user.nvim-gps")
require("user.nvim-tree")
require("user.which-key")
require("user.gitsigns")
require("user.nvim-lsp-installer")
require("user.cmp")
require("user.alpha")
require("user.nvim-treesitter")
require("user.impatient")
require("user.numb")
require("user.nvim_comment")
