require("settings.color")
-- vim.cmd("colorscheme dracula")
-- vim.cmd("colorscheme hybrid")
-- vim.cmd("colorscheme kanagawa")
-- vim.cmd("colorscheme rose-pine")
-- vim.cmd("colorscheme catppuccin")
-- vim.cmd("colorscheme gruvbox")
-- vim.cmd("colorscheme tokyonight")
-- vim.cmd("colorscheme neohybrid")
