return {
    -- NOTE: This is only here to install the LSP Servers properly and kinda easy. This is not quite needed if
    --  you install them manually. In case you don't wanna lookup where all those LSP Servers are located and 
    --  how to install them, just look at the Registry of Mason itself: github.com/mason-org/mason-registry
    --  and download the ones you want. Then you can remove this Plugin.
    --  However, Mason installs all LSP Servers under $HOME/.local/share/nvim/mason/bin. So in case you need
    --  those LSP Servers somewhere else (e.g. Emacs), you might want to add that path to your $PATH variable.
    --  $ export PATH="$HOME/.local/share/nvim/mason/bin:$PATH"
    --  Technically, you could use Mason to install a new LSP Server and then use it in Emacs or other Editors,
    --  or even remove Mason after installing the LSP Servers you want, like its done here. 
    --
    -- NOTE: Enable to install new LSP Servers (automatically)
    --
    -- "mason-org/mason.nvim",
    -- event = "VeryLazy",
    -- -- dependencies = {
    -- --     { "mason-org/mason-lspconfig.nvim", opts={} },
    -- --     { "neovim/nvim-lspconfig", opts={} },
    -- -- },
    -- opts = {
    --     ensure_installed = {
    --         "lua_ls",
    --         "pyright-langserver",
    --         "gopls",
    --         "clangd",
    --         "rust_analyzer",
    --         "bashls",
    --         "ts_ls",
    --         "cssls",
    --         "tailwindcssls",
    --         "htmlls",
    --         "jdtls",
    --     },
    -- },
}
